title: LUI Field Guide
remote_theme: pmarsceill/just-the-docs
color_scheme: cmap
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - CodingMultipleUses.md
  - TransitionalRedevelopmentParcels.md
  - 1100_Residential.md
  - 1200_Commercial.md
  - 1300_Institutional.md
  - 1400_Industrial.md
  - 1500_TransportationCommunicationsUtilities.md
  - 2000_Agriculture.md
  - 3000_OpenSpace.md
  - 5000_Water.md
  - 9999_NotClassifiable.md
exclude:
  - README.md

# Aux links for the upper right navigation
aux_links:
  "LUI Field Guide on GitHub":
    - "//github.com/CMAP-REPOS/LUI-wiki"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/CMAP-REPOS/LUI-wiki" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
